global:
  sendAnonymousUsage: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
    
  https:
    address: ":443"

api:
  dashboard: true
  insecure: true

log:
  level: INFO
  format: common

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

  file:
    filename: "/etc/traefik/config.yml"
    watch: true

  consulCatalog:
    refreshInterval: 10s
    connectAware: true
    serviceName: "traefik"
    prefix: traefik
    exposedByDefault: true
    endpoint: 
      address: "consul:8500"
      scheme: "http"
      tls:
        insecureSkipVerify: true
    watch: true
    defaultRule: "Host(`{{ normalize .Name }}.ingesoftcurso.localhost`)"