services:
  mysql:
    build: ../db/
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_CHARSET=utf8
      - MYSQL_COLLATION=utf8_general_ci
    container_name: databaseexample
    networks:
      - red
    #command: --default-authentication-plugin=mysql_native_password

networks:
  red:
    external: true