services:
  redis:
    image: redis:7-bullseye
    restart: always
    volumes:
      - ~/redis/_data:/data
      - ~/redis/_data/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf
    ports:
      - 6379:6379
    networks:
      - red

networks:
  red:
    external: true
    driver: bridge

